### ISSUE TITLE
Initialization Error

### ISSUE THREAD

**Issue by jpmorgan98** [kokkos/pykokkos#2]
Hello all
I am trying to get `pykokkos` running and launch a simple hello world. I built the two `kokkos` shared libraries and set the requested environment variables but get the initialization error: `ImportError: libkokkoscore.so.3.1.1: cannot open shared object file: No such file or directory`. See attachment of my terminal for where the environment variables are pointing and that I do have the requested files in said directories. I am sure it's something really simple but, what have I done wrong?  Note: I am trying to use the pre-compiled version of `pykokkos-base` from the repo instead of building that separately.

From reading the other thread it sounds like there are alot of updates coming down the pike so if this issue is addressed in upcoming commits I can hold off!

Thank you guys so much!

![gnome-shell-screenshot-hc4dtg](https://user-images.githubusercontent.com/67020956/151227070-e8947d8e-d887-44be-aa07-d0575bb4ca15.png)

**Comment by NaderAlAwar** [comment]
Are you on `main` or `develop`? If you're on main, do you have the most recent commit?

**Comment by jpmorgan98** [comment]
Yes I am on main. I was in an older commit so I fetched, remade the conda environment, and tried again.

This time it failed in `pykokkos/bindings/bindings/__init__.py` as I don't have `pykokkos-base` built  (no kokkos library).

So I just changed the one line on that one init file back to: `from . import bindings as kokkos` (I am guessing this will make it use the pre-compiled base?) and I am now getting the same issue as before (`ImportError: libkokkoscore.so.3.1.1: cannot open shared object file: No such file or directory`). Should I just bite the bullet and build `pykokkos-base`?

Thank you!

**Comment by NaderAlAwar** [comment]
Yeah you should build  `pykokkos-base`. The reason you're getting that error is probably because the `libpykokkos` in the repo was built with a different compiler than the one on your system.

If you're worried about the installation process failing, I would say try to build `pykokkos-base` with only OpenMP enabled first (which should be fast) to see if everything is working fine, so something like this:

`python setup.py install -- -DENABLE_LAYOUTS=ON -DENABLE_MEMORY_TRAITS=OFF -DENABLE_VIEW_RANKS=3 -DENABLE_CUDA=OFF -DENABLE_THREADS=OFF -DENABLE_OPENMP=ON`

Then you can install PyKokkos. If that works, then you try rebuilding `pykokkos-base` with CUDA enabled.

Let me know if you need help or have other questions about any of this.

**Comment by jpmorgan98** [comment]
That got the hello world listed on the README to work but now when I try and run the example for the views, also on the README, I am having some more trouble:

The installation process I am currently using:
1. Create Conda environment off of `pykokkos-base` and `pykokkos` requirements
2. install `pykokkos-base` using the command provided above (my understanding is that this will build the requisite Kokkos libraries in it's sub directories)
3. set the PATH variables to the requested folders in `PATH_TO_ENV/lib/python3.9/site-packages/pykokkos_base-0.0.7-py3.9-linux-x86_64.egg/lib/ or include/`
4. Run the file

I get the following error when it's trying to do the initial compilation:
```
KeyError: 'PK_KOKKOS_LIB_PATH_OMP'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Kokkos allocation "" is being deallocated after Kokkos::finalize was called

Traceback functionality not available

Aborted (core dumped)
```

Thanks again for all the help!

**Comment by NaderAlAwar** [comment]
That's good to hear! The key error you're seeing is because `PK_KOKKOS_LIB_PATH_OMP` was not found in the environment. Are you sure you set the environment variable properly?

As for the math functions, all you have to do is `import math` somewhere in your code and you should be able to use them normally, e.g. `math.sin()`. PyKokkos will map them to the appropriate C++ function. That said I haven't tested all math functions,  so let me know if you run into any issues when you try that.

**Comment by jpmorgan98** [comment]
You know when you are so sure it's not the simplest thing possible then it ends up being that thing, must be a firday!

Thanks again for bearing with me

**Comment by jpmorgan98** [comment]
I am actually still getting a runtime error but a different one now! I tried this on multiple examples and a few test files and all came back with this:

```
RuntimeError: Unable to cast Python instance of type <class 'kokkos.libpykokkos.KokkosView_int32_HostSpace_LayoutRight_1'> to C++ type 'Kokkos::View<int*, Kokkos::LayoutRight, Kokkos::HostSpace>'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Kokkos allocation "" is being deallocated after Kokkos::finalize was called

Traceback functionality not available

Aborted (core dumped)
```

Sorry: I should test more before I close these.

**Comment by NaderAlAwar** [comment]
Are you using the same compiler you used to compile `pykokkos-base`? By default, PyKokkos will use `g++`

**Comment by jpmorgan98** [comment]
That was the issue! It was something weird with my manual v auto settings in `update-alternatives`. I am running some kernels now but everytime I do I get this warning:
```
Kokkos::OpenMP::initialize WARNING: You are likely oversubscribing your CPU cores.
                                    Detected: 1 cores per node.
                                    Detected: 1 MPI_ranks per node.
                                    Requested: 16 threads per process.
```
What ever this issue is it is causing the kernel to only run on one thread (I have an 8 core 16 thread CPU). Also when the computation ends successfully I get that generic failure message every time, including for the test functions.
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Kokkos allocation "" is being deallocated after Kokkos::finalize was called

Traceback functionality not available

Aborted (core dumped)
```

Thank you again, I owe you

**Comment by NaderAlAwar** [comment]
That's a Kokkos warning, I haven't seen it before. When you import `pykokkos-base`, it will automatically set some OpenMP environment variables (see [here](https://github.com/kokkos/pykokkos-base/blob/a195eaaaf0cef83c9b98eb317a4cdb0bb4bcf4f5/kokkos/__init__.py.in#L198)).

The other error shouldn't cause you any issues, it's due to some views being deallocated after Kokkos::finalize() is called. I fixed it on the develop branch and I'll merge the fix at some point.
